version: '2'

services:
  docker_docker_maccms:
    container_name: docker_docker_maccms
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - 9103:80
    volumes:
      - ./web:/var/www/html
      - ./data:/var/lib/mysql
